# Generated by Django 6.0.1 on 2026-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('platform', 'Platform'), ('course', 'Course'), ('video', 'Video'), ('article', 'Article'), ('book', 'Book'), ('documentation', 'Documentation')], default='platform', max_length=20),
        ),
    ]
