# Generated by Django 6.0.1 on 2026-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_resource_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to resource logo/icon'),
        ),
    ]
