# Generated by Django 6.0.1 on 2026-04-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_add_documentation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short label shown on the chip, e.g. 'Medicine'", max_length=50)),
                ('keyword', models.CharField(help_text="Text inserted into the textarea, e.g. 'medicine & health'", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Custom logo URL. Leave blank to use the default icon for this type.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('platform', 'Platform'), ('course', 'Course'), ('video', 'Video'), ('article', 'Article'), ('book', 'Book'), ('documentation', 'Documentation'), ('guide', 'Guide')], default='platform', max_length=20),
        ),
    ]
